.PHONY: versions

versions:
	@set -eu
	@echo "== Tool versions =="
	@echo "captured_utc: $$(date -u +%FT%TZ)"
	@echo "git_commit: $$(git rev-parse --short HEAD 2>/dev/null || echo NA)"
	@echo ""
	@echo "-- OS --"
	@uname -a || true
	@echo ""
	@echo "-- Core --"
	@command -v bash >/dev/null 2>&1 && bash --version 2>/dev/null | sed -n '1p' || echo "bash: NOT FOUND"
	@command -v make >/dev/null 2>&1 && make --version 2>/dev/null | sed -n '1p' || echo "make: NOT FOUND"
	@command -v rsync >/dev/null 2>&1 && rsync --version 2>/dev/null | sed -n '1p' || echo "rsync: NOT FOUND"
	@command -v grep >/dev/null 2>&1 && grep --version 2>/dev/null | sed -n '1p' || echo "grep: NOT FOUND"
	@command -v sed  >/dev/null 2>&1 && sed  --version 2>/dev/null | sed -n '1p' || echo "sed: NOT FOUND"
	@command -v awk  >/dev/null 2>&1 && awk  --version 2>/dev/null | sed -n '1p' || echo "awk: NOT FOUND"
	@echo ""
	@echo "-- HTS / alignment --"
	@command -v bwa >/dev/null 2>&1 && { bwa 2>&1 | awk -F': ' '/^Version:/{print "bwa " $$2; found=1} END{if(!found) print "bwa (version not detected)"}' || true; } || echo "bwa: NOT FOUND"

	@command -v samtools >/dev/null 2>&1 && samtools --version 2>/dev/null | sed -n '1,2p' || echo "samtools: NOT FOUND"
	@command -v bcftools >/dev/null 2>&1 && bcftools --version 2>/dev/null | sed -n '1,2p' || echo "bcftools: NOT FOUND"
	@command -v bgzip >/dev/null 2>&1 && bgzip --version 2>/dev/null | sed -n '1p' || echo "bgzip: NOT FOUND"
	@command -v tabix >/dev/null 2>&1 && tabix --version 2>/dev/null | sed -n '1p' || echo "tabix: NOT FOUND"
	@command -v bedtools >/dev/null 2>&1 && bedtools --version 2>/dev/null | sed -n '1p' || echo "bedtools: NOT FOUND"
	@echo ""
	@echo "-- Java / GATK --"
	@command -v java >/dev/null 2>&1 && java -version 2>&1 | sed -n '1,3p' || echo "java: NOT FOUND"
	@command -v gatk >/dev/null 2>&1 && gatk --version 2>/dev/null || echo "gatk: NOT FOUND"
	@echo ""
	@echo "-- Python --"
	@command -v python3 >/dev/null 2>&1 && python3 --version 2>/dev/null || echo "python3: NOT FOUND"
	@command -v pip3 >/dev/null 2>&1 && pip3 --version 2>/dev/null || echo "pip3: NOT FOUND"
	@echo ""
	@echo "-- QC helpers (optional) --"
	@command -v fastqc >/dev/null 2>&1 && fastqc --version 2>/dev/null || echo "fastqc: NOT FOUND"
	@command -v multiqc >/dev/null 2>&1 && multiqc --version 2>/dev/null || echo "multiqc: NOT FOUND"
	@echo ""
	@echo "-- R (optional) --"
	@command -v R >/dev/null 2>&1 && R --version 2>/dev/null | sed -n '1,2p' || echo "R: NOT FOUND"
