#!/usr/bin/env Rscript

# Build the A117V spike-in LoD CSV and manuscript TeX tables.

get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  if (length(file_arg) > 0L) {
    return(dirname(normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/", mustWork = TRUE)))
  }
  normalizePath(getwd(), winslash = "/", mustWork = TRUE)
}

script_dir <- get_script_dir()
repo_root <- normalizePath(file.path(script_dir, "..", ".."), winslash = "/", mustWork = TRUE)

legacy_csv <- Sys.getenv(
  "PRNP_A117V_LEGACY_CSV",
  unset = file.path(repo_root, "legacy", "src", "windows", "2025-05-03_dilution_QC_analysis", "A117V_table.csv")
)

manifest_tsv <- Sys.getenv(
  "PRNP_MANIFEST",
  unset = file.path(repo_root, "authoritative_files", "manifest.tsv")
)

results_csv <- Sys.getenv(
  "PRNP_A117V_LOD_CSV",
  unset = file.path(repo_root, "results", "sequencing_qc", "a117v_spike_in_lod_table.csv")
)

main_tex <- Sys.getenv(
  "PRNP_A117V_LOD_TEX",
  unset = file.path(repo_root, "manuscript", "tables", "main", "table_a117v_spike_in_lod.tex")
)

all_tables_tex <- Sys.getenv(
  "PRNP_ALL_TABLES_TEX",
  unset = file.path(repo_root, "manuscript", "tables", "all_tables_with_legends", "all_tables.tex")
)

source_table_rel <- "legacy/src/windows/2025-05-03_dilution_QC_analysis/A117V_table.csv"

required_legacy_cols <- c(
  "Sample",
  "Variant",
  "dbSNP ID",
  "Chromosome",
  "Position",
  "REF",
  "ALT",
  "Mutation Type",
  "Read Depth (DP)",
  "REF Count",
  "ALT Count",
  "AAF (%)",
  "Base Quality",
  "Mapping Quality",
  "REF Forward Count",
  "REF Reverse Count",
  "ALT Forward Count",
  "ALT Reverse Count"
)

sample_map <- data.frame(
  legacy_label = c("A117V 0.5% spike-in", "A117V 1% spike-in"),
  sample_id = c("NA995A05_undil", "NA99A1_undil"),
  stringsAsFactors = FALSE
)

load_manifest_labels <- function(path, sample_ids) {
  if (!file.exists(path)) {
    stop("Sample manifest does not exist: ", path)
  }

  manifest <- read.delim(
    path,
    sep = "\t",
    header = TRUE,
    stringsAsFactors = FALSE,
    check.names = FALSE
  )

  required_cols <- c("sample_id", "display_label")
  missing_cols <- setdiff(required_cols, names(manifest))
  if (length(missing_cols) > 0L) {
    stop("Sample manifest is missing required column(s): ", paste(missing_cols, collapse = ", "))
  }

  rows <- manifest$sample_id %in% sample_ids
  if (any(duplicated(manifest$sample_id[rows]))) {
    stop("Sample manifest has duplicate rows for A117V spike-in IDs")
  }

  labels <- setNames(manifest$display_label[rows], manifest$sample_id[rows])
  labels <- labels[sample_ids]

  missing_labels <- names(labels)[is.na(labels) | labels == "" | labels == "NA"]
  if (length(missing_labels) > 0L) {
    stop("Sample manifest is missing display_label values for: ", paste(missing_labels, collapse = ", "))
  }

  labels
}

as_numeric_col <- function(x, column_name) {
  out <- suppressWarnings(as.numeric(x))
  if (any(is.na(out))) {
    stop("Column has non-numeric value(s): ", column_name)
  }
  out
}

exact_ci_percent <- function(alt_count, depth) {
  ci <- binom.test(alt_count, depth, conf.level = 0.95)$conf.int
  as.numeric(ci) * 100
}

latex_safe <- function(x) {
  x <- ifelse(is.na(x), "NA", as.character(x))
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([%&_#$])", "\\\\\\1", x)
  x
}

fmt_int <- function(x) {
  format(as.integer(round(as.numeric(x))), big.mark = "", scientific = FALSE)
}

fmt_two <- function(x) {
  sprintf("%.2f", as.numeric(x))
}

fmt_vaf_ci <- function(vaf, lower, upper) {
  paste0(fmt_two(vaf), " (", fmt_two(lower), "--", fmt_two(upper), ")")
}

render_table <- function(table_data) {
  rows <- apply(table_data, 1L, function(row) {
    paste0(
      "      ",
      paste(
        latex_safe(c(
          row[["display_label"]],
          row[["variant"]],
          row[["dbsnp_id"]],
          row[["chromosome"]],
          fmt_int(row[["position"]]),
          row[["ref"]],
          row[["alt"]],
          row[["mutation_type"]],
          fmt_int(row[["read_depth_dp"]]),
          fmt_int(row[["ref_count"]]),
          fmt_int(row[["alt_count"]]),
          fmt_vaf_ci(row[["vaf_percent"]], row[["vaf_ci_lower_percent"]], row[["vaf_ci_upper_percent"]]),
          fmt_int(row[["base_quality"]]),
          fmt_two(row[["mapping_quality"]]),
          fmt_int(row[["ref_forward_count"]]),
          fmt_int(row[["ref_reverse_count"]]),
          fmt_int(row[["alt_forward_count"]]),
          fmt_int(row[["alt_reverse_count"]])
        )),
        collapse = " & "
      ),
      " \\\\"
    )
  })

  c(
    "% Generated by src/sequencing_qc/make_a117v_spike_in_lod_table.R",
    "\\begin{table}[t]",
    "  \\centering",
    "  \\resizebox{\\textwidth}{!}{",
    "    \\begin{tabular}{%",
    "        l  % Sample",
    "        l  % Variant",
    "        l  % dbSNP ID",
    "        l  % Chromosome",
    "        r  % Position",
    "        c  % REF",
    "        c  % ALT",
    "        l  % Mutation Type",
    "        r  % Read Depth (DP)",
    "        r  % REF Count",
    "        r  % ALT Count",
    "        l  % VAF (exact 95\\% CI, \\%)",
    "        r  % Base Quality",
    "        r  % Mapping Quality",
    "        r  % REF Forward Count",
    "        r  % REF Reverse Count",
    "        r  % ALT Forward Count",
    "        r  % ALT Reverse Count",
    "      }",
    "      \\toprule",
    "      Sample & Variant & dbSNP ID & Chromosome & Position & REF & ALT",
    "      & Mutation Type & Read Depth (DP) & REF Count & ALT Count",
    "      & VAF (exact 95\\% CI, \\%) & Base Quality & Mapping Quality",
    "      & REF Forward Count & REF Reverse Count",
    "      & ALT Forward Count & ALT Reverse Count \\\\",
    "      \\midrule",
    rows,
    "      \\bottomrule",
    "    \\end{tabular}",
    "  }",
    "  \\vspace{0.5em}",
    paste0(
      "  \\caption{\\textbf{A117V spike-in analysis for targeted-sequencing sensitivity assessment.} ",
      "\\textbf{A117V high} denotes the higher-input sample; its observed VAF was 1.32\\% (exact 95\\% binomial CI of 1.07--1.62\\%). ",
      "\\textbf{A117V low} denotes the lower-input sample; its observed VAF was 0.81\\% (exact 95\\% binomial CI of 0.57--1.13\\%). ",
      "Exact binomial confidence intervals were calculated by the Clopper--Pearson method using ALT count as x and read depth as n. ",
      "\\textbf{A117V low} was used as the conservative LoD anchor for downstream somatic calling.}"
    ),
    "  \\label{tab:a117v_spike_in_lod}",
    "\\end{table}",
    "",
    "\\clearpage"
  )
}

replace_embedded_a117v_table <- function(path, table_lines) {
  if (!file.exists(path)) {
    stop("Combined manuscript table file does not exist: ", path)
  }

  raw <- readBin(path, what = "raw", n = file.info(path)$size)
  text <- rawToChar(raw)
  eol <- if (grepl("\r\n", text, fixed = TRUE)) "\r\n" else "\n"
  replacement <- paste(table_lines[table_lines != "\\clearpage"], collapse = eol)
  lines <- strsplit(text, "\r\n|\n", perl = TRUE)[[1]]

  label_idx <- grep("\\\\label\\{tab:a117v_spike_in_lod\\}", lines)
  if (length(label_idx) != 1L) {
    stop("Expected exactly one A117V table label in: ", path)
  }

  begin_candidates <- grep("^\\s*\\\\begin\\{table\\}", lines[seq_len(label_idx)])
  end_candidates <- grep("^\\s*\\\\end\\{table\\}", lines[seq.int(label_idx, length(lines))])
  if (length(begin_candidates) == 0L || length(end_candidates) == 0L) {
    stop("Could not find the enclosing A117V table block in: ", path)
  }

  start <- begin_candidates[length(begin_candidates)]
  end <- label_idx + end_candidates[1] - 1L
  if (start > 1L && grepl("^% Generated by src/sequencing_qc/make_a117v_spike_in_lod_table\\.R\\s*$", lines[start - 1L])) {
    start <- start - 1L
  }

  before <- if (start > 1L) lines[seq_len(start - 1L)] else character(0)
  after <- if (end < length(lines)) lines[seq.int(end + 1L, length(lines))] else character(0)
  updated_lines <- c(before, strsplit(replacement, eol, fixed = TRUE)[[1]], after)
  updated <- paste(updated_lines, collapse = eol)
  if (grepl("(\r\n|\n)$", text, perl = TRUE)) {
    updated <- paste0(updated, eol)
  }
  writeBin(charToRaw(updated), con = path)
}

if (!file.exists(legacy_csv)) {
  stop("A117V source CSV does not exist: ", legacy_csv)
}

legacy <- read.csv(
  legacy_csv,
  header = TRUE,
  stringsAsFactors = FALSE,
  colClasses = "character",
  check.names = FALSE
)

missing_legacy_cols <- setdiff(required_legacy_cols, names(legacy))
if (length(missing_legacy_cols) > 0L) {
  stop("A117V source CSV is missing required column(s): ", paste(missing_legacy_cols, collapse = ", "))
}

legacy_idx <- match(sample_map$legacy_label, legacy[["Sample"]])
if (any(is.na(legacy_idx))) {
  stop("A117V source CSV is missing expected legacy label(s): ", paste(sample_map$legacy_label[is.na(legacy_idx)], collapse = ", "))
}

selected <- legacy[legacy_idx, , drop = FALSE]
labels <- load_manifest_labels(manifest_tsv, sample_map$sample_id)

depth <- as_numeric_col(selected[["Read Depth (DP)"]], "Read Depth (DP)")
alt_count <- as_numeric_col(selected[["ALT Count"]], "ALT Count")
ref_count <- as_numeric_col(selected[["REF Count"]], "REF Count")
vaf_percent <- alt_count / depth * 100
legacy_vaf <- as_numeric_col(selected[["AAF (%)"]], "AAF (%)")
if (any(abs(vaf_percent - legacy_vaf) > 1e-9)) {
  stop("Calculated VAF does not match the legacy AAF (%) source values")
}

ci <- t(mapply(exact_ci_percent, alt_count, depth))

out <- data.frame(
  sample_id = sample_map$sample_id,
  display_label = unname(labels),
  legacy_label = sample_map$legacy_label,
  variant = selected[["Variant"]],
  dbsnp_id = selected[["dbSNP ID"]],
  chromosome = selected[["Chromosome"]],
  position = as_numeric_col(selected[["Position"]], "Position"),
  ref = selected[["REF"]],
  alt = selected[["ALT"]],
  mutation_type = selected[["Mutation Type"]],
  read_depth_dp = depth,
  ref_count = ref_count,
  alt_count = alt_count,
  vaf_percent = vaf_percent,
  vaf_ci_lower_percent = ci[, 1],
  vaf_ci_upper_percent = ci[, 2],
  vaf_ci_method = "Exact binomial (Clopper-Pearson)",
  base_quality = as_numeric_col(selected[["Base Quality"]], "Base Quality"),
  mapping_quality = as_numeric_col(selected[["Mapping Quality"]], "Mapping Quality"),
  ref_forward_count = as_numeric_col(selected[["REF Forward Count"]], "REF Forward Count"),
  ref_reverse_count = as_numeric_col(selected[["REF Reverse Count"]], "REF Reverse Count"),
  alt_forward_count = as_numeric_col(selected[["ALT Forward Count"]], "ALT Forward Count"),
  alt_reverse_count = as_numeric_col(selected[["ALT Reverse Count"]], "ALT Reverse Count"),
  source_table = source_table_rel,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

dir.create(dirname(results_csv), showWarnings = FALSE, recursive = TRUE)
dir.create(dirname(main_tex), showWarnings = FALSE, recursive = TRUE)

options(digits = 15)
write.csv(out, file = results_csv, row.names = FALSE, quote = TRUE)

table_lines <- render_table(out)
writeLines(table_lines, con = main_tex, useBytes = TRUE)
replace_embedded_a117v_table(all_tables_tex, table_lines)

cat("Wrote:\n")
cat("  ", results_csv, "\n", sep = "")
cat("  ", main_tex, "\n", sep = "")
cat("  ", all_tables_tex, "\n", sep = "")
