library(tidyverse)
library(readxl)

project_root <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
scratch_root <- file.path(project_root, "scratch", "ddpcr-new")
analysis_root <- file.path(scratch_root, "analysis")
xlsx_path <- file.path(analysis_root, "results", "ddPCR", "SNV_data_final.xlsx")
output_dir <- file.path(scratch_root, "tables", "sample_number")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

mutation_order <- c("D178N", "E200K", "P102L")

safe_max <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) NA_real_ else max(x)
}

format_vaf <- function(x) {
  ifelse(
    is.na(x),
    "NA",
    format(round(x, 3), nsmall = 3, scientific = FALSE, trim = TRUE)
  )
}

as_true_flag <- function(x) {
  if (is.logical(x)) {
    return(!is.na(x) & x)
  }
  tolower(trimws(as.character(x))) %in% c("true", "1", "yes")
}

escape_html <- function(x) {
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub("\"", "&quot;", x, fixed = TRUE)
  x
}

write_html_table <- function(.data, output_path, caption) {
  headers <- paste0("<th>", escape_html(names(.data)), "</th>", collapse = "")
  body <- vapply(seq_len(nrow(.data)), function(i) {
    cells <- vapply(names(.data), function(col) {
      paste0("<td>", escape_html(ifelse(is.na(.data[[col]][i]), "", .data[[col]][i])), "</td>")
    }, character(1))
    paste0("<tr>", paste0(cells, collapse = ""), "</tr>")
  }, character(1))

  html <- c(
    "<!doctype html>",
    "<html><head><meta charset=\"utf-8\">",
    "<style>",
    "body{font-family:Arial,sans-serif;margin:24px;color:#111827}",
    "table{border-collapse:collapse;font-size:12px}",
    "th,td{border:1px solid #d1d5db;padding:4px 6px;text-align:right}",
    "th:first-child,td:first-child,th:last-child,td:last-child{text-align:left}",
    "th{background:#f3f4f6;position:sticky;top:0}",
    "caption{caption-side:top;text-align:left;font-weight:700;margin-bottom:8px}",
    "</style></head><body>",
    paste0("<table><caption>", escape_html(caption), "</caption>"),
    paste0("<thead><tr>", headers, "</tr></thead>"),
    paste0("<tbody>", paste0(body, collapse = "\n"), "</tbody>"),
    "</table></body></html>"
  )

  writeLines(html, output_path)
}

write_basic_tex <- function(.data, output_path) {
  escape_latex <- function(x) {
    x <- as.character(x)
    x <- gsub("\\\\", "\\\\textbackslash{}", x)
    x <- gsub("&", "\\\\&", x)
    x <- gsub("%", "\\\\%", x)
    x <- gsub("_", "\\\\_", x)
    x
  }

  tex_cells <- .data %>% mutate(across(everything(), ~ escape_latex(.x)))
  header <- paste(escape_latex(names(.data)), collapse = " & ")
  rows <- apply(tex_cells, 1, function(row) paste0(paste(row, collapse = " & "), " \\\\"))
  lines <- c(
    "% Auto-generated by scratch/ddpcr_pooled_scale/scripts/ddpcr_sample_number_corrected.R",
    paste0("\\begin{tabular}{", paste(rep("l", ncol(.data)), collapse = ""), "}"),
    paste0(header, " \\\\"),
    rows,
    "\\end{tabular}"
  )
  writeLines(lines, output_path)
}

ensure_mutation_cols <- function(.data, prefix) {
  for (mutation in mutation_order) {
    col <- paste0(prefix, mutation)
    if (!col %in% names(.data)) {
      .data[[col]] <- NA_real_
    }
  }
  .data
}

participant_levels <- function(x) {
  tibble(name = unique(as.character(x))) %>%
    mutate(
      .group = case_when(
        grepl("^CJD", name) ~ 1L,
        grepl("^Control", name) ~ 2L,
        TRUE ~ 3L
      ),
      .number = readr::parse_number(name)
    ) %>%
    arrange(.group, .number, name) %>%
    pull(name)
}

build_summary <- function(ddpcr) {
  lob_lod_status_rows <- ddpcr %>%
    mutate(
      pass_lob_lod = as_true_flag(detected_above_LoB) & as_true_flag(detected_above_LoD),
      known_heterozygous_e200k = participant == "CJD30" & mutation == "E200K",
      .mutation_order = match(mutation, mutation_order),
      .status_label = if_else(known_heterozygous_e200k, paste0(mutation, "*"), mutation)
    ) %>%
    filter(pass_lob_lod)

  participant_lob_lod_status <- lob_lod_status_rows %>%
    distinct(participant, group, .mutation_order, .status_label) %>%
    arrange(participant, .mutation_order, .status_label) %>%
    group_by(participant, group) %>%
    summarise(`LoB+LoD pass` = paste(.status_label, collapse = "; "), .groups = "drop")

  group_lob_lod_status <- lob_lod_status_rows %>%
    filter(!known_heterozygous_e200k) %>%
    distinct(group, .mutation_order, .status_label) %>%
    arrange(group, .mutation_order, .status_label) %>%
    group_by(group) %>%
    summarise(`LoB+LoD pass` = paste(.status_label, collapse = "; "), .groups = "drop")

  analysed_samples <- ddpcr %>%
    distinct(participant, group, brain_region) %>%
    count(participant, group, name = "analysed_samples")

  by_mut <- ddpcr %>%
    group_by(participant, group, mutation) %>%
    summarise(
      analysed = n_distinct(brain_region),
      max_maf = safe_max(fractional_abundance),
      .groups = "drop"
    )

  counts_wide <- by_mut %>%
    select(participant, group, mutation, analysed) %>%
    pivot_wider(names_from = mutation, values_from = analysed, names_prefix = "analysed_") %>%
    ensure_mutation_cols("analysed_") %>%
    mutate(across(starts_with("analysed_"), ~ replace_na(.x, 0L)))

  max_wide <- by_mut %>%
    select(participant, group, mutation, max_maf) %>%
    pivot_wider(names_from = mutation, values_from = max_maf, names_prefix = "max_maf_") %>%
    ensure_mutation_cols("max_maf_")

  ddpcr_by_patient <- analysed_samples %>%
    left_join(counts_wide, by = c("participant", "group")) %>%
    left_join(max_wide, by = c("participant", "group")) %>%
    left_join(participant_lob_lod_status, by = c("participant", "group")) %>%
    mutate(
      name = participant,
      `LoB+LoD pass` = replace_na(`LoB+LoD pass`, "None")
    ) %>%
    rowwise() %>%
    mutate(
      max_maf_overall = if_else(
        name == "CJD30",
        safe_max(c(max_maf_D178N, max_maf_P102L)),
        safe_max(c(max_maf_D178N, max_maf_E200K, max_maf_P102L))
      )
    ) %>%
    ungroup() %>%
    select(
      name,
      analysed_samples,
      analysed_D178N, analysed_E200K, analysed_P102L,
      max_maf_D178N, max_maf_E200K, max_maf_P102L,
      max_maf_overall,
      `LoB+LoD pass`,
      group
    )

  group_totals <- ddpcr_by_patient %>%
    group_by(group) %>%
    summarise(
      analysed_samples = sum(analysed_samples, na.rm = TRUE),
      analysed_D178N = sum(analysed_D178N, na.rm = TRUE),
      analysed_E200K = sum(analysed_E200K, na.rm = TRUE),
      analysed_P102L = sum(analysed_P102L, na.rm = TRUE),
      max_maf_D178N = safe_max(max_maf_D178N),
      max_maf_E200K = safe_max(replace(max_maf_E200K, name == "CJD30", NA_real_)),
      max_maf_P102L = safe_max(max_maf_P102L),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(
      max_maf_overall = safe_max(c(max_maf_D178N, max_maf_E200K, max_maf_P102L)),
      name = case_when(
        group == "prion" ~ "All CJD",
        group == "control" ~ "All controls",
        TRUE ~ paste("All", group)
      )
    ) %>%
    ungroup() %>%
    left_join(group_lob_lod_status, by = "group") %>%
    mutate(`LoB+LoD pass` = replace_na(`LoB+LoD pass`, "None")) %>%
    select(
      name,
      analysed_samples,
      analysed_D178N, analysed_E200K, analysed_P102L,
      max_maf_D178N, max_maf_E200K, max_maf_P102L,
      max_maf_overall,
      `LoB+LoD pass`,
      group
    )

  bind_rows(
    ddpcr_by_patient %>%
      filter(group == "prion") %>%
      mutate(name = factor(name, levels = participant_levels(name))) %>%
      arrange(name),
    ddpcr_by_patient %>%
      filter(group == "control") %>%
      mutate(name = factor(name, levels = participant_levels(name))) %>%
      arrange(name),
    group_totals %>%
      arrange(match(group, c("prion", "control")))
  ) %>%
    select(-group) %>%
    mutate(
      name = as.character(name),
      across(where(is.numeric), ~ round(.x, 3))
    )
}

ddpcr <- readxl::read_excel(xlsx_path) %>%
  mutate(
    participant = as.character(participant),
    group = as.character(group),
    mutation = as.character(mutation),
    brain_region = as.character(brain_region),
    is_pooled = as_true_flag(is_pooled),
    detected_above_LoB = as_true_flag(detected_above_LoB),
    detected_above_LoD = as_true_flag(detected_above_LoD)
  )

summary_including_pooled_rows <- build_summary(ddpcr)
summary_excluding_technical_pooled_rows <- build_summary(ddpcr %>% filter(!is_pooled))

summary_tex <- summary_including_pooled_rows %>%
  mutate(
    max_maf_D178N = format_vaf(max_maf_D178N),
    max_maf_E200K = if_else(name == "CJD30", paste0(format_vaf(max_maf_E200K), "*"), format_vaf(max_maf_E200K)),
    max_maf_P102L = format_vaf(max_maf_P102L),
    max_maf_overall = format_vaf(max_maf_overall)
  )

readr::write_csv(summary_including_pooled_rows, file.path(output_dir, "ddPCR_sample_number_corrected.csv"))
readr::write_csv(
  summary_excluding_technical_pooled_rows,
  file.path(output_dir, "ddPCR_sample_number_excluding_technical_pooled_rows_sensitivity.csv")
)
write_basic_tex(summary_tex, file.path(output_dir, "ddpcr_sample_number_basic_corrected.tex"))
write_html_table(
  summary_tex,
  file.path(output_dir, "ddPCR_sample_number_corrected.html"),
  "Corrected ddPCR sample-number summary"
)

pass_rows <- ddpcr %>%
  filter(detected_above_LoB, detected_above_LoD) %>%
  arrange(mutation, participant, brain_region)

readr::write_csv(
  pass_rows,
  file.path(output_dir, "sample_region_lob_lod_pass_rows_corrected.csv")
)
