#!/usr/bin/env Rscript

# Build the table of spike-in SNPs recovered in both mixtures.

get_script_dir <- function() {
  args <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("^--file=", args, value = TRUE)
  dirname(normalizePath(sub("^--file=", "", file_arg[1]), winslash = "/", mustWork = TRUE))
}

script_dir <- get_script_dir()
repo_root <- normalizePath(file.path(script_dir, "..", ".."), winslash = "/", mustWork = TRUE)

recovery_tsv <- file.path(repo_root, "results2", "spikein", "read_recovery", "mixture_read_recovery.tsv")
calls_tsv <- file.path(repo_root, "results2", "spikein", "logs", "final", "final_marker_calls.tsv")
markers_tsv <- file.path(repo_root, "results2", "spikein", "markers", "informative_markers.tsv")
lod_tsv <- file.path(repo_root, "results2", "spikein", "read_recovery", "empirical_lod.tsv")
output_tex <- file.path(script_dir, "table_spikein_snp_recovery.tex")

read_tsv <- function(path) {
  if (!file.exists(path)) {
    stop("Input does not exist: ", path)
  }
  read.delim(path, sep = "\t", header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
}

require_columns <- function(data, columns, source) {
  missing <- setdiff(columns, names(data))
  if (length(missing) > 0L) {
    stop(source, " is missing: ", paste(missing, collapse = ", "))
  }
}

exact_ci_percent <- function(alt_count, depth) {
  as.numeric(binom.test(alt_count, depth, conf.level = 0.95)$conf.int) * 100
}

latex_safe <- function(x) {
  x <- ifelse(is.na(x) | x == "", "NA", as.character(x))
  x <- gsub("([%&_#$])", "\\\\\\1", x)
  vapply(
    strsplit(x, ">", fixed = TRUE),
    function(parts) paste(parts, collapse = "\\textgreater{}"),
    character(1)
  )
}

fmt_int <- function(x) {
  format(as.integer(x), big.mark = "", scientific = FALSE)
}

fmt_two <- function(x) {
  sprintf("%.2f", as.numeric(x))
}

fmt_vaf_ci <- function(vaf, lower, upper) {
  paste0(fmt_two(vaf), " (", fmt_two(lower), "--", fmt_two(upper), ")")
}

render_table <- function(data) {
  rows <- apply(data, 1L, function(row) {
    values <- c(
      row[["sample_label"]], row[["marker_label"]], row[["dbsnp_id"]],
      row[["chromosome"]], fmt_int(row[["position"]]), row[["ref"]], row[["alt"]],
      fmt_int(row[["usable_depth"]]), fmt_int(row[["ref_count"]]),
      fmt_int(row[["alt_count"]]),
      fmt_vaf_ci(row[["vaf_percent"]], row[["ci_lower_percent"]], row[["ci_upper_percent"]]),
      fmt_two(row[["mutect2_vaf_percent"]]), fmt_two(row[["alt_mean_bq"]]),
      fmt_two(row[["alt_mean_mq"]]), fmt_int(row[["alt_forward"]]),
      fmt_int(row[["alt_reverse"]]), row[["filter_status"]]
    )
    paste0("      ", paste(latex_safe(values), collapse = " & "), " \\\\")
  })

  c(
    "% Generated by manuscript2/tables2/make_spikein_snp_recovery_table.R",
    "\\begin{table}[t]",
    "  \\centering",
    "  \\resizebox{\\textwidth}{!}{",
    "    \\begin{tabular}{lllrcccrrrllrrrrl}",
    "      \\toprule",
    "      Sample & Marker & dbSNP ID & Chromosome & Position & REF & ALT",
    "      & Usable depth & REF count & ALT count & bam-readcount VAF (exact 95\\% CI, \\%)",
    "      & Mutect2-estimated VAF (\\%) & ALT mean BQ & ALT mean MQ",
    "      & ALT forward & ALT reverse & Filter \\\\",
    "      \\midrule",
    rows,
    "      \\bottomrule",
    "    \\end{tabular}",
    "  }",
    "  \\vspace{0.5em}",
    paste0(
      "  \\caption{\\textbf{Spike-in SNP recovery across both mixtures.} ",
      "The table includes fixed SNP markers whose exact alleles passed read-level QC, Mutect2 and ",
      "FilterMutectCalls in both A117V high and A117V low. bam-readcount VAFs use ALT count divided ",
      "by usable A/C/G/T depth; Mutect2-estimated VAF is reported separately. The empirical complete-pipeline ",
      "LoD is 26/3891 (0.668\\%), defined by chr20:4693455 G\\textgreater{}A in A117V low.}"
    ),
    "  \\label{tab:spikein_snp_recovery}",
    "\\end{table}",
    "",
    "\\clearpage"
  )
}

# Read the fixed markers, direct counts and final exact-allele calls.
recovery <- read_tsv(recovery_tsv)
calls <- read_tsv(calls_tsv)
markers <- read_tsv(markers_tsv)
lod <- read_tsv(lod_tsv)

require_columns(
  recovery,
  c(
    "marker_id", "chromosome", "position", "ref", "alt", "category", "sample_role",
    "sample_id", "usable_depth", "ref_count", "alt_count", "alt_vaf", "alt_forward",
    "alt_reverse", "alt_mean_bq", "alt_mean_mq", "read_level_recovered"
  ),
  "Mixture recovery table"
)
require_columns(
  calls,
  c("marker_id", "role", "sample", "filtered_pass", "filtered_vaf", "filter_status"),
  "Final marker-call table"
)
require_columns(markers, c("marker_id", "dbsnp_id"), "Informative marker table")
require_columns(
  lod,
  c(
    "supporting_marker", "supporting_sample", "bam_readcount_alt_count",
    "bam_readcount_usable_depth", "filtermutectcalls_status"
  ),
  "Empirical LoD table"
)

# Retain markers that pass the final caller in both authoritative mixture roles.
passing_calls <- calls[calls$filtered_pass == "yes", , drop = FALSE]
roles_by_marker <- split(passing_calls$role, passing_calls$marker_id)
shared_markers <- names(roles_by_marker)[vapply(
  roles_by_marker,
  function(roles) identical(sort(unique(roles)), c("high", "low")),
  logical(1)
)]
if (length(shared_markers) == 0L) {
  stop("No exact SNP allele passed in both mixtures")
}

passing_calls <- passing_calls[passing_calls$marker_id %in% shared_markers, , drop = FALSE]
names(passing_calls)[names(passing_calls) == "role"] <- "sample_role"
names(passing_calls)[names(passing_calls) == "sample"] <- "sample_id"

# Join the final caller status to the direct-count evidence.
table_data <- merge(
  recovery[recovery$read_level_recovered == "True", , drop = FALSE],
  passing_calls[, c("marker_id", "sample_role", "sample_id", "filtered_vaf", "filter_status")],
  by = c("marker_id", "sample_role", "sample_id")
)
table_data <- table_data[table_data$marker_id %in% shared_markers, , drop = FALSE]
if (nrow(table_data) != 2L * length(shared_markers)) {
  stop("Expected one high and one low direct-count row for every shared marker")
}

table_data <- merge(table_data, markers[, c("marker_id", "dbsnp_id")], by = "marker_id")
table_data$dbsnp_id[is.na(table_data$dbsnp_id) | table_data$dbsnp_id == ""] <- "NA"
table_data$sample_label <- ifelse(table_data$sample_role == "high", "A117V high", "A117V low")
table_data$marker_label <- ifelse(
  table_data$category == "a117v_positive_control",
  "A117V",
  paste(table_data$chromosome, table_data$position, paste0(table_data$ref, ">", table_data$alt))
)

# Calculate direct-count intervals and retain the Mutect2-estimated VAF separately.
intervals <- t(mapply(exact_ci_percent, table_data$alt_count, table_data$usable_depth))
table_data$vaf_percent <- as.numeric(table_data$alt_vaf) * 100
table_data$ci_lower_percent <- intervals[, 1]
table_data$ci_upper_percent <- intervals[, 2]
table_data$mutect2_vaf_percent <- as.numeric(table_data$filtered_vaf) * 100

# Verify that the canonical LoD row is present among the displayed PASS calls.
lod_row <- table_data[
  table_data$marker_id == lod$supporting_marker & table_data$sample_id == lod$supporting_sample, ,
  drop = FALSE
]
lod_matches <- c(
  nrow(lod_row) == 1L,
  lod$filtermutectcalls_status == "PASS",
  lod_row$alt_count == lod$bam_readcount_alt_count,
  lod_row$usable_depth == lod$bam_readcount_usable_depth
)
if (!all(lod_matches)) {
  stop("Displayed rows do not contain the canonical empirical LoD observation")
}

# Keep paired high and low rows together in genomic order.
role_order <- match(table_data$sample_role, c("high", "low"))
table_data <- table_data[order(table_data$position, role_order), , drop = FALSE]
writeLines(render_table(table_data), con = output_tex, useBytes = TRUE)

cat("Wrote ", output_tex, "\n", sep = "")
cat("Included ", length(shared_markers), " SNPs and ", nrow(table_data), " rows\n", sep = "")
